name: Application 2

on:
  push:
    branches:
      - main
    paths:
      - "app2/**"
      - ".github/**/app2.yaml"
  # allows manual trigger on the default branch
  workflow_dispatch:
  # allow workflow call to support deploy all
  workflow_call:

jobs:
  to_test:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute to test
        run: echo "Execute to test for Application 2"
  
  to_prod:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute to prod
        run: echo "Execute to prod for Application 2"
  
  to_pen_test:
    if: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' }}
    runs-on: ubuntu-latest
    steps:
      - name: Execute to penetration testing
        run: echo "Execute to penetration testing for Application 2"
