name: admin-console - Build and Deploy to GKE

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      env:
        type: choice
        required: true
        description: The environment where the app is deployed to.
        options: 
        - test
        - prod
        - pentest
  workflow_call:
    inputs:
      env:
        type: string
jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    outputs:
      git_version: ${{ steps.build.outputs.git_version }}
    steps:
      - name: checkout
        run: echo "Execute checkout"

      - name: build and push container
        id: build
        run: |-
          echo "git_version=frombuild" >> "$GITHUB_OUTPUT"

          echo "Execute build and push container"

  deploy-test:
    if:  ${{ github.event_name == 'push' || ((github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call') && (github.event.inputs.env == 'test' || github.event.inputs.env == 'prod')) }}
    needs: build
    name: Deploy to test
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: deploy to test
        run: echo "Execute deploy to test with version ${{ needs.build.outputs.git_version }}"

      - name: run tests on test env
        run: echo "Execute run tests on test env"

      - name: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: ./integration_tests/cucumber/reports

  deploy-prod:
    if:  ${{ github.event_name == 'push' || ((github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call') && github.event.inputs.env == 'prod') }}
    needs: deploy-test
    name: Deploy to prod
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: deploy to prod
        run: echo "Execute deploy to prod"
      - name: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: ./integration_tests/cucumber/reports

  deploy-pentest:
    # only allow to run when:
    #     1. manually triggered or triggered by other workflows, the input `env == "pentest"` is required
    if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call') && github.event.inputs.env == 'pentest' }}
    needs: build
    name: Deploy to pentest
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: deploy to pentest
        run: echo "Execute deploy to prod"

      - name: upload
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-artifacts
          path: ./integration_tests/cucumber/reports
