name: Penetration Testing All

on:
  # only allows manual trigger on the default branch
  workflow_dispatch:

jobs:
  app1:
    uses: ./.github/workflows/app1.yaml
  app2:
    uses: ./.github/workflows/app2.yaml
