name: Penetration Testing All

on:
  # only allows manual trigger on the default branch
  workflow_dispatch:

jobs:
  app1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v
      - name: deploy app 1
        uses: ./.github/workflows/app1.yml
  app2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy app 1
        uses: ./.github/workflows/app2.yml
