name: admin-console - Build and Deploy to GKE

on:
  push:
    branches:
      - main

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        run: echo "Execute checkout"

  job2:
    name: job2
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        run: echo "Execute checkout"
  
      - name: Fail the job
        run: |
          echo "Something went wrong!"
          exit 1

  
  job3:
    name: job3
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write
      id-token: write
    steps:
      - name: checkout
        run: echo "Execute checkout"
  
  notification:
    name: success
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [job1, job2, job3]
    permissions:
      contents: write
      id-token: write
    steps:  
      - name: Check job statuses
        run: |
          if [ "${{ needs.job1.result }}" == "failure" ] || [ "${{ needs.job2.result }}" == "failure" ] || [ "${{ needs.job3.result }}" == "failure" ]; then
            exit 1  # Fails notification if any job failed
          else
            exit 0
          fi

      - name: notify-success
        run: echo "success"
        if: ${{ success() }}

      - name: notify-fail-canceled
        run: echo "fail-canceled"
        if: ${{ failure() || cancelled() }}